blueprints/authc/routes.py
import json
import random
import string

import requests

import httplib2
from blueprints import app, session
from flask import session as login_session
from flask import (Blueprint, flash, make_response, redirect, render_template,
                   request, url_for)
from models import User
from oauth2client.client import FlowExchangeError, flow_from_clientsecrets

authc = Blueprint('authc', __name__)


# Create anti-forgery state token
@authc.route('/login')
def showLogin():
    """Show Login Page"""
    state = ''.join(
                    random.choice(string.ascii_uppercase + string.digits)
                    for x in xrange(32))
    login_session['state'] = state

    return render_template('login.html', STATE=state)


@authc.route('/gconnect', methods=['POST'])
def gconnect():
    """Google Login"""
    # Validate state token
    if request.args.get('state') != login_session['state']:
        response = make_response(json.dumps('Invalid state parameter.'), 401)
        response.headers['Content-Type'] = 'application/json'
        return response
    # Obtain authorization code
    code = request.data

    try:
        # Upgrade the authorization code into a credentials object
        oauth_flow = flow_from_clientsecrets('google_auth.json', scope='')
        oauth_flow.redirect_uri = 'postmessage'
        credentials = oauth_flow.step2_exchange(code)
    except FlowExchangeError:
        response = make_response(
            json.dumps('Failed to upgrade the authorization code.'), 401)
        response.headers['Content-Type'] = 'application/json'
        return response

    # Check that the access token is valid.
    access_token = credentials.access_token
    url = ('https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=%s'
           % access_token)
    h = httplib2.Http()
    result = json.loads(h.request(url, 'GET')[1])
    # If there was an error in the access token info, abort.
    if result.get('error') is not None:
        response = make_response(json.dumps(result.get('error')), 500)
        response.headers['Content-Type'] = 'application/json'
        return response

    # Verify that the access token is used for the intended user.
    gplus_id = credentials.id_token['sub']
    if result['user_id'] != gplus_id:
        response = make_response(
            json.dumps("Token's user ID doesn't match given user ID."), 401)
        response.headers['Content-Type'] = 'application/json'
        return response

    # Verify that the access token is valid for this app.
    if result['issued_to'] != app.config['GOOGLE_CLIENT_ID']:
        response = make_response(
            json.dumps("Token's client ID does not match app's."), 401)
        print "Token's client ID does not match app's."
        response.headers['Content-Type'] = 'application/json'
        return response

    stored_access_token = login_session.get('access_token')
    stored_gplus_id = login_session.get('gplus_id')
    if stored_access_token is not None and gplus_id == stored_gplus_id:
        response = make_response(
            json.dumps('Current user is already connected.'), 200)
        response.headers['Content-Type'] = 'application/json'
        return response

    # Store the access token in the session for later use.
    login_session['access_token'] = credentials.access_token
    login_session['gplus_id'] = gplus_id

    # Get user info
    userinfo_url = "https://www.googleapis.com/oauth2/v1/userinfo"
    params = {'access_token': credentials.access_token, 'alt': 'json'}
    answer = requests.get(userinfo_url, params=params)

    data = answer.json()

    login_session['provider'] = 'google'
    login_session['username'] = data['name']
    login_session['email'] = data['email']

    user_id = getUserID(login_session['email'])
    if not user_id:
        user_id = createUser(login_session)
    login_session['user_id'] = user_id

    flash("Now logged in as %s" % login_session['username'])
    return "You have been logged in"


@authc.route('/gdisconnect')
def gdisconnect():
    """Google Logout"""
    access_token = login_session.get('access_token')
    if access_token is None:
        print 'Access Token is None'
        response = make_response(
            json.dumps('Current user not connected.'), 401)
        response.headers['Content-Type'] = 'application/json'
        return response
    print 'In gdisconnect access token is %s', access_token
    print 'User name is: '
    print login_session['username']
    url = ('https://accounts.google.com/o/oauth2/revoke?token=%s'
           % login_session['access_token'])
    h = httplib2.Http()
    result = h.request(url, 'GET')[0]
    print 'result is '
    print result
    return "You have been logged out"


@authc.route('/fbconnect', methods=['POST'])
def fbconnect():
    """Facebook Login"""
    if request.args.get('state') != login_session['state']:
        response = make_response(json.dumps('Invalid state parameter.'), 401)
        response.headers['Content-Type'] = 'application/json'
        return response
    access_token = request.data
    print "access token received %s " % access_token

    app_id = json.loads(open('facebook_auth.json', 'r').read())[
        'web']['app_id']
    app_secret = json.loads(
        open('facebook_auth.json', 'r').read())['web']['app_secret']
    url = ('https://graph.facebook.com/oauth/access_token'
           '?grant_type=fb_exchange_token'
           '&client_id=%s&client_secret=%s&fb_exchange_token=%s'
           % (app_id, app_secret, access_token))
    h = httplib2.Http()
    result = h.request(url, 'GET')[1]

    # Use token to get user info from API
    userinfo_url = "https://graph.facebook.com/v2.8/me"
    '''
        Due to the formatting for the result from the server token exchange
        we have to split the token first on commas and select the first index
        which gives us the key : value for the server access token then we
        split it on colons to pull out the actual token value and replace the
        remaining quotes with nothing so that it can be used directly in the
        graph api calls
    '''
    token = result.split(',')[0].split(':')[1].replace('"', '')

    url = ('https://graph.facebook.com/v2.8/me'
           '?access_token=%s&fields=name,id,email'
           % token)
    h = httplib2.Http()
    result = h.request(url, 'GET')[1]
    data = json.loads(result)
    login_session['provider'] = 'facebook'
    login_session['username'] = data["name"]
    login_session['email'] = data["email"]
    login_session['facebook_id'] = data["id"]

    # The token must be stored in the login_session in order to properly logout
    login_session['access_token'] = token

    # see if user exists
    user_id = getUserID(login_session['email'])
    if not user_id:
        user_id = createUser(login_session)
    login_session['user_id'] = user_id

    flash("Now logged in as %s" % login_session['username'])
    print login_session
    return "You have been logged in"


@authc.route('/fbdisconnect')
def fbdisconnect():
    """Facebook Logout"""
    facebook_id = login_session['facebook_id']
    # The access token must me included to successfully logout
    access_token = login_session['access_token']
    url = ('https://graph.facebook.com/%s/permissions?access_token=%s'
           % (facebook_id, access_token))
    h = httplib2.Http()
    result = h.request(url, 'DELETE')[1]
    return "You have been logged out"


@authc.route('/disconnect')
def disconnect():
    """Disconnect based on provider"""
    if 'provider' in login_session:
        if login_session['provider'] == 'google':
            gdisconnect()
            del login_session['gplus_id']
        if login_session['provider'] == 'facebook':
            fbdisconnect()
            del login_session['facebook_id']
        del login_session['username']
        del login_session['email']
        del login_session['user_id']
        del login_session['provider']
        del login_session['access_token']
        flash("You have successfully logged out")
        return redirect(url_for('site.showHome'))
    else:
        flash("You were not logged in")
        return redirect(url_for('site.showHome'))


# User Functions
def createUser(login_session):
    newUser = User(name=login_session['username'],
                   email=login_session['email'])
    session.add(newUser)
    session.commit()
    user = session.query(User).filter_by(email=login_session['email']).one()
    return user.id


def getUserInfo(user_id):
    user = session.query(User).filter_by(id=user.id).one()
    return user


def getUserID(email):
    try:
        user = session.query(User).filter_by(email=email).one()
        return user.id
    except:
        return None

blueprints/site/routes.py
from blueprints import session
from flask import session as login_session
from flask import Blueprint, flash, redirect, render_template, request, url_for
from forms import ItemForm
from functools import wraps
from models import Category, Item
from sqlalchemy import desc

site = Blueprint('site', __name__)


# Login Required Decorator
def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'username' not in login_session:
            flash("Please login to continue")
            return redirect(url_for('authc.showLogin'))
        return f(*args, **kwargs)
    return decorated_function


@site.route('/')
def showHome():
    """This will show all categories with the latest items"""
    categories = session.query(Category).all()
    items = session.query(Item).order_by(desc(Item.id)).limit(9)

    return render_template(
           'home.html', categories=categories,
           items=items, login_session=login_session)


@site.route('/catalog')
def catalogRedirect():
    """This will redirect /catalog to showHome()"""
    return redirect(url_for('site.showHome'), code=301)


@site.route('/catalog/<string:category_name>/items')
def showCategory(category_name):
    """This will show all items in a category"""
    categories = session.query(Category).all()
    category = session.query(Category).filter_by(name=category_name).one_or_none()
    if category is None:
        flash("Category does not exist")
        return redirect(url_for('site.showHome'))
    items = session.query(Item).filter_by(category=category).all()

    return render_template(
           'category.html', categories=categories,
           category=category, items=items)


@site.route('/catalog/<string:category_name>/<int:item_id>')
def showItem(category_name, item_id):
    """This will show an item"""
    category = session.query(Category).filter_by(name=category_name).one_or_none()
    if category is None:
        flash("Category does not exist")
        return redirect(url_for('site.showHome'))
    item = session.query(Item).filter_by(id=item_id, category=category).one_or_none()
    if item is None:
        flash("Item does not exist")
        return redirect(url_for('site.showHome'))

    return render_template('item.html', category=category, item=item)


@site.route('/catalog/new', methods=['GET', 'POST'])
@login_required
def newItem():
    categories = session.query(Category).all()

    # This loads the ItemForm into a local variable
    form = ItemForm(request.form)

    if request.method == 'GET':
        # This will render a form to add a new item
        return render_template('newitem.html',
                               categories=categories, form=form)
    if request.method == 'POST':
        # This checks whether the form passes validation
        if form.validate():
            # This will add a new item to the database
            category = session.query(Category).filter_by(
                       name=request.form['category']).one_or_none()
            if category is None:
                flash("Get out of dev tools, hacker!")
                return redirect(url_for('site.showHome'))

            item = Item(name=request.form['name'],
                        description=request.form['description'],
                        category=category,
                        user_id=login_session['user_id'])
            session.add(item)
            session.commit()

            return redirect(url_for(
                            'site.showItem',
                            category_name=item.category.name, item_id=item.id))
        else:
            # This will run if the form fails validation
            return render_template('newitem.html',
                                   categories=categories, form=form)


@site.route('/catalog/<int:item_id>/edit', methods=['GET', 'POST'])
@login_required
def editItem(item_id):
    categories = session.query(Category).all()
    item = session.query(Item).filter_by(id=item_id).one_or_none()
    if item is None:
        flash("Item does not exist")
        return redirect(url_for('site.showHome'))

    # Checks if the current user is not the owner of the item
    if login_session['user_id'] != item.user_id:
        flash("You're not authorized to edit this item")
        return redirect(url_for('site.showHome'))

    # This loads the ItemForm into a local variable
    form = ItemForm(request.form)

    if request.method == 'GET':
        # This will render a form to edit an item
        form.name.data = item.name
        form.description.data = item.description
        return render_template(
               'edititem.html',
               categories=categories, item=item, form=form)

    if request.method == 'POST':
        # This checks whether the form passes validation
        if form.validate():
            # This will commit the item edit to the database
            item.category = item.category
            if request.form['name']:
                item.name = request.form['name']
            if request.form['description']:
                item.description = request.form['description']
            if request.form['category']:
                item.category = session.query(Category).filter_by(
                                name=request.form['category']).one_or_none()
                if item.category is None:
                    flash("Get out of dev tools, hacker!")
                    return redirect(url_for('site.showHome'))
            session.add(item)
            session.commit()

            return redirect(url_for(
                            'site.showItem',
                            category_name=item.category.name, item_id=item.id))
        else:
            # This will run if the form fails validation
            return render_template(
                   'edititem.html',
                   categories=categories, item=item, form=form)


@site.route('/catalog/<item_id>/delete', methods=['GET', 'POST'])
@login_required
def deleteItem(item_id):
    item = session.query(Item).filter_by(id=item_id).one_or_none()
    if item is None:
        flash("Item does not exist")
        return redirect(url_for('site.showHome'))

    # Checks if the current user is not the owner of the item
    if login_session['user_id'] != item.user_id:
        flash("You're not authorized to delete this item")
        return redirect(url_for('site.showHome'))

    if request.method == 'GET':
        # This will render a form to delete an item
        return render_template('deleteitem.html', item=item)
    if request.method == 'POST':
        # This will delete an item from the database
        session.delete(item)
        session.commit()
        return redirect(url_for('site.showHome'))

blueprints/templates/_formhelpers.html
{% macro render_error_div(field) %}
  {% if field.errors %}
  <div class="alert alert-danger" role="alert">{{ field.errors[0] }}</div>
  {% endif %}
{% endmacro %}

blueprints/templates/category.html
{% extends "main.html" %}
{% block content %}
<div class="col-sm-4">
  {% include "categorysidebar.html" %}
</div>
<div class="col-sm-8">
  <h1>{{ category.name|title|replace("-", " ") }} Items ({{ items|length }} items)</h1>
  {% for item in items %}
  <p>
    <a href="{{ url_for('site.showItem', category_name=item.category.name, item_id=item.id) }}">{{ item.name }}</a>
  </p>
  {% endfor %}
</div>
{% endblock %}

blueprints/templates/categorysidebar.html
<h1>Categories</h1>
{% for category in categories %}
<p>
  <a href="{{ url_for('site.showCategory', category_name=category.name) }}">{{ category.name|title|replace("-", " ") }}</a>
</p>
{% endfor %}

blueprints/templates/deleteitem.html
{% extends "main.html" %}
{% block content %}
<div class="col-sm-6">
  <h1>Delete Item</h1>
  <p>Are you sure you want to delete {{item.name}}?</p>

  <form action="#" method="post">
    <button type="submit" class="btn btn-danger" id="submit" type="submit">Delete</button>
  </form>
</div>
{% endblock %}

blueprints/templates/edititem.html
{% extends "main.html" %}
{% block content %}
<div class="row col-sm-6">
  <h1>Edit Item</h1>
  {% from "_formhelpers.html" import render_error_div %}
  <form action="{{ url_for('site.editItem', item_id=item.id )}}" method="post">
    <div class="form-group">
      {{ form.name.label }}
      {{ form.name(class="form-control mb-1",
                   placeholder="Name of the item",
                   maxlength="50") }}
      {{ render_error_div(form.name) }}

      {{ form.description.label }}
      {{ form.description(class="form-control mb-1",
                          placeholder="Description of the item",
                          maxlength="1500",
                          rows="5") }}
      {{ render_error_div(form.description) }}
      
      <div class="select mb-1">
        <select name="category">
        {% for category in categories %}
            <option value="{{ category.name }}"{% if item.category == category %}selected="selected"{% endif %}>{{ category.name|title|replace("-", " ") }}</option>
        {% endfor %}
        </select>
      </div>

      <button type="submit" class="btn btn-orange" id="submit" type="submit">Update</button>
    </div>
  </form>
</div>
{% endblock %}

blueprints/templates/home.html
{% extends "main.html" %}
{% block content %}
<div class="col-sm-4">
  {% include "categorysidebar.html" %}
</div>
<div class="col-sm-8">
  <h1>Latest Items</h1>
  {% if session.user_id %}
  <p><i><a href="{{ url_for('site.newItem') }}">Add Item</a></i></p>
  {% endif %}
  {% for item in items %}
  <p>
    <a href="{{ url_for('site.showItem', category_name=item.category.name, item_id=item.id) }}">{{ item.name }} </a>
    <i>({{ item.category.name|title|replace("-", " ") }})</i>
  </p>
  {% endfor %}
</div>
{% endblock %}

blueprints/templates/item.html
{% extends "main.html" %}
{% block content %}
<h1>{{ item.name }}</h1>
<p>Description: {{ item.description }}</p>
{% if session.user_id == item.user_id %}
<p>
  <a href="{{ url_for('site.editItem', item_id=item.id) }}">Edit |</a>
  <a href="{{ url_for('site.deleteItem', item_id=item.id) }}">Delete</a>
</p>
{% endif %}
<p><i>Category: <a href="{{ url_for('site.showCategory', category_name=item.category.name) }}">{{ item.category.name|title|replace("-", " ") }}</a></i></p>
{% endblock %}

blueprints/templates/login.html
{% extends "main.html" %}
{% block head %}
<!--LOAD PRE-REQUISITES FOR GOOGLE SIGN IN -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="//apis.google.com/js/platform.js?onload=start"></script>
<!-- END PRE-REQUISITES FOR GOOGLE SIGN IN -->
{% endblock %}
{% block content %}
<h1>Login</h1>
<h5>Sign in with an account of your choice</h5>
<!-- GOOGLE SIGN IN BUTTON-->
<div id="signinButton">
  <span class="g-signin"
    data-scope="openid email"
    data-clientid="{{ config['GOOGLE_CLIENT_ID'] }}"
    data-redirecturi="postmessage"
    data-accesstype="offline"
    data-cookiepolicy="single_host_origin"
    data-callback="signInCallback"
    data-approvalprompt="force">
  </span>
</div>
<!--END GOOGLE SIGN IN BUTTON -->
<!-- FACEBOOK SIGN IN BUTTON-->
<fb:login-button scope="public_profile,email" onlogin="sendTokenToServer();">
<a href='javascript:sendTokenToServer()'>Login with Facebook</a>
</fb:login-button>
<!--END FACEBOOK SIGN IN BUTTON-->
<div id="result"></div>


<!-- GOOGLE SIGN IN SCRIPT-->
<script>
function signInCallback(authResult) {
  if (authResult['code']) {
    // Hide the sign-in button now that the user is authorized
    $('#signinButton').attr('style', 'display: none');
    // Send the one-time-use code to the server, if the server responds, write a 'login successful' message to the web page and then redirect back to the main restaurants page
    $.ajax({
      type: 'POST',
      url: '/gconnect?state={{STATE}}',
      processData: false,
      data: authResult['code'],
      contentType: 'application/octet-stream; charset=utf-8',
      success: function(result) {
        // Handle or verify the server response if necessary.
        if (result) {
            window.location.href = "/";
        } else if (authResult['error']) {
            console.log('There was an error: ' + authResult['error']);
        } else {
            $('#result').html('Failed to make a server-side call. Check your configuration and console.');
        }
      }
    });
  }
}
</script>
<!--END GOOGLE SIGN IN SCRIPT-->

<!--FACEBOOK SIGN IN SCRIPT-->
<script>
window.fbAsyncInit = function() {
  FB.init({
    appId      : '136354693689965',
    cookie     : true,  // enable cookies to allow the server to access 
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.2' // use version 2.2
  });
};
// Load the SDK asynchronously
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
// Here we run a very simple test of the Graph API after login is
// successful.  See statusChangeCallback() for when this call is made.
function sendTokenToServer() {
  var access_token = FB.getAuthResponse()['accessToken'];
  console.log(access_token)
  console.log('Welcome!  Fetching your information.... ');
  FB.api('/me', function(response) {
    console.log('Successful login for: ' + response.name);
    $.ajax({
      type: 'POST',
      url: '/fbconnect?state={{STATE}}',
      processData: false,
      data: access_token,
      contentType: 'application/octet-stream; charset=utf-8',
      success: function(result) {
        // Handle or verify the server response if necessary.
        if (result) {
          window.location.href = "/";
        } else {
          $('#result').html('Failed to make a server-side call. Check your configuration and console.');
        }
      }
    });
 });
}
</script>
<!--END FACEBOOK SIGN IN SCRIPT-->
{% endblock %}

blueprints/templates/main.html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <title>Catalog App</title>

    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='dist/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{{ url_for('static', filename='dist/bootstrap/css/ie10-viewport-bug-workaround.css') }}" rel="stylesheet">

    <!-- Custom styles -->
    <link href="{{ url_for('static', filename='css/app.css') }}" rel="stylesheet">

    {% block head %}
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" id="site-name" href="{{ url_for('site.showHome') }}">Catalog App</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            {% if session.user_id %}
            <a href="{{ url_for('authc.disconnect') }}"><button type="button" class="btn btn-orange navbar-btn">Logout</button></a>
            {% else %}
            <a href="{{ url_for('authc.showLogin') }}"><button type="button" class="btn btn-orange navbar-btn">Login</button></a>
            {% endif %}
        </div>
      </div>
    </nav>

    <div class="flash">
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      <ul>
      {% for message in messages %}
        <li><strong>{{ message }}</strong></li>
      {% endfor %}
      </ul>
      {% endif %}
      {% endwith %}
    </div>

    <div class="container" id="main-container">
      <div class="col-sm-12" id="main-grid">
        {% block content %}
        {% endblock %}
      </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{{ url_for('static', filename='dist/bootstrap/js/bootstrap.min.js') }}"></script>


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{{ url_for('static', filename='dist/bootstrap/js/ie10-viewport-bug-workaround.js') }}"></script>

  </body>
</html>

blueprints/templates/newitem.html
{% extends "main.html" %}
{% block content %}
<h1>Add Item</h1>
<div class="row col-sm-6">
  {% from "_formhelpers.html" import render_error_div %}
  <form action="#" method="post">
    <div class="form-group">
      {{ form.name.label }}
      {{ form.name(class="form-control mb-1",
                   placeholder="Name of the item",
                   maxlength="50") }}
      {{ render_error_div(form.name) }}

      {{ form.description.label }}
      {{ form.description(class="form-control mb-1",
                          placeholder="Description of the item",
                          maxlength="1500",
                          rows="5") }}
      {{ render_error_div(form.description) }}
      
      <div class="select mb-1">
        <select name="category">
        {% for category in categories %}
            <option value="{{ category.name }}">{{ category.name|title|replace("-", " ") }}</option>
        {% endfor %}
        </select>
      </div>
      <button type="submit" class="btn btn-orange" id="submit" type="submit">Create</button>
    </div>
  </form>
</div>
{% endblock %}